name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.13"]
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pylint

      - name: Run pylint and capture score
        id: pylint
        run: |
          SCORE_LINE=$(pylint $(git ls-files '*.py') | tee pylint.log | tail -n 2 | head -n 1)
          echo "Pylint score line: $SCORE_LINE"
          SCORE=$(echo "$SCORE_LINE" | sed -n 's/.*rated at \([0-9.]*\)\/10.*/\1/p')
          echo "Extracted score: $SCORE"
          if (( $(echo "$SCORE < 9.0" | bc -l) )); then
            echo "❌ Pylint score too low: $SCORE"
            exit 1
          else
            echo "✅ Pylint passed with score: $SCORE"
            exit 0
          fi

      - name: Print pylint summary
        run: |
          echo "=== Pylint Summary ==="
          tail -n 10 pylint.log

      - name: Upload full pylint log
        uses: actions/upload-artifact@v4
        with:
          name: pylint-full-log
          path: pylint.log
